/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "s3eMATSDK_autodefs.h"
#include "s3eEdk.h"
#include "s3eMATSDK.h"
//Declarations of Init and Term functions
extern s3eResult s3eMATSDKInit();
extern void s3eMATSDKTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static void MATStartMobileAppTracker_wrap(const char* adId, const char* convKey)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATStartMobileAppTracker"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATStartMobileAppTracker, 2, adId, convKey);
}

static void MATSDKParameters_wrap()
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSDKParameters"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSDKParameters, 0);
}

static void MATTrackInstall_wrap()
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATTrackInstall"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATTrackInstall, 0);
}

static void MATTrackUpdate_wrap()
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATTrackUpdate"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATTrackUpdate, 0);
}

static void MATTrackInstallWithReferenceId_wrap(const char* refId)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATTrackInstallWithReferenceId"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATTrackInstallWithReferenceId, 1, refId);
}

static void MATTrackActionForEventIdOrName_wrap(const char* eventIdOrName, bool isId, const char* refId)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATTrackActionForEventIdOrName"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATTrackActionForEventIdOrName, 3, eventIdOrName, isId, refId);
}

static void MATTrackActionForEventIdOrNameItems_wrap(const char* eventIdOrName, bool isId, const MATArray* items, const char* refId, double revenueAmount, const char* currencyCode, uint8 transactionState)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATTrackActionForEventIdOrNameItems"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATTrackActionForEventIdOrNameItems, 7, eventIdOrName, isId, items, refId, revenueAmount, currencyCode, transactionState);
}

static void MATTrackAction_wrap(const char* eventIdOrName, bool isId, double revenue, const char* currency)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATTrackAction"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATTrackAction, 4, eventIdOrName, isId, revenue, currency);
}

static void MATSetPackageName_wrap(const char* packageName)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetPackageName"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetPackageName, 1, packageName);
}

static void MATSetCurrencyCode_wrap(const char* currencyCode)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetCurrencyCode"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetCurrencyCode, 1, currencyCode);
}

static void MATSetOpenUDID_wrap(const char* openUDID)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetOpenUDID"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetOpenUDID, 1, openUDID);
}

static void MATSetUserId_wrap(const char* userId)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetUserId"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetUserId, 1, userId);
}

static void MATSetRevenue_wrap(double revenue)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetRevenue"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetRevenue, 1, revenue);
}

static void MATSetSiteId_wrap(const char* siteId)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetSiteId"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetSiteId, 1, siteId);
}

static void MATSetTRUSTeId_wrap(const char* tpid)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetTRUSTeId"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetTRUSTeId, 1, tpid);
}

static void MATSetAge_wrap(int age)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetAge"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetAge, 1, age);
}

static void MATSetGender_wrap(int gender)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetGender"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetGender, 1, gender);
}

static void MATSetLocation_wrap(double latitude, double longitude, double altitude)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetLocation"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetLocation, 3, latitude, longitude, altitude);
}

static void MATSetDelegate_wrap(bool enable)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetDelegate"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetDelegate, 1, enable);
}

static void MATSetUseHTTPS_wrap(bool enable)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetUseHTTPS"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetUseHTTPS, 1, enable);
}

static void MATSetJailbroken_wrap(bool isJailbroken)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetJailbroken"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetJailbroken, 1, isJailbroken);
}

static void MATSetShouldAutoDetectJailbroken_wrap(bool shouldAutoDetect)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetShouldAutoDetectJailbroken"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetShouldAutoDetectJailbroken, 1, shouldAutoDetect);
}

static void MATSetShouldAutoGenerateMacAddress_wrap(bool shouldAutoGenerate)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetShouldAutoGenerateMacAddress"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetShouldAutoGenerateMacAddress, 1, shouldAutoGenerate);
}

static void MATSetShouldAutoGenerateODIN1Key_wrap(bool shouldAutoGenerate)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetShouldAutoGenerateODIN1Key"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetShouldAutoGenerateODIN1Key, 1, shouldAutoGenerate);
}

static void MATSetShouldAutoGenerateOpenUDIDKey_wrap(bool shouldAutoGenerate)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetShouldAutoGenerateOpenUDIDKey"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetShouldAutoGenerateOpenUDIDKey, 1, shouldAutoGenerate);
}

static void MATSetUseCookieTracking_wrap(bool useCookieTracking)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetUseCookieTracking"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetUseCookieTracking, 1, useCookieTracking);
}

static void MATStartAppToAppTracking_wrap(const char* targetAppId, const char* advertiserId, const char* offerId, const char* publisherId, bool shouldRedirect)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATStartAppToAppTracking"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATStartAppToAppTracking, 5, targetAppId, advertiserId, offerId, publisherId, shouldRedirect);
}

static void MATSetRedirectUrl_wrap(const char* redirectUrl)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetRedirectUrl"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetRedirectUrl, 1, redirectUrl);
}

static void MATSetAppleAdvertisingIdentifier_wrap(const char* advertiserId)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetAppleAdvertisingIdentifier"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetAppleAdvertisingIdentifier, 1, advertiserId);
}

static void MATSetAppleVendorIdentifier_wrap(const char* vendorId)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetAppleVendorIdentifier"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetAppleVendorIdentifier, 1, vendorId);
}

static void MATSetShouldAutoGenerateAppleVendorIdentifier_wrap(bool shouldAutoGenerate)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetShouldAutoGenerateAppleVendorIdentifier"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetShouldAutoGenerateAppleVendorIdentifier, 1, shouldAutoGenerate);
}

static void MATSetShouldAutoGenerateAppleAdvertisingIdentifier_wrap(bool shouldAutoGenerate)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetShouldAutoGenerateAppleAdvertisingIdentifier"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetShouldAutoGenerateAppleAdvertisingIdentifier, 1, shouldAutoGenerate);
}

static void MATSetDebugMode_wrap(bool shouldDebug)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetDebugMode"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetDebugMode, 1, shouldDebug);
}

static void MATSetAllowDuplicates_wrap(bool allowDuplicates)
{
    IwTrace(MATSDK_VERBOSE, ("calling s3eMATSDK func on main thread: MATSetAllowDuplicates"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)MATSetAllowDuplicates, 1, allowDuplicates);
}

#define MATStartMobileAppTracker MATStartMobileAppTracker_wrap
#define MATSDKParameters MATSDKParameters_wrap
#define MATTrackInstall MATTrackInstall_wrap
#define MATTrackUpdate MATTrackUpdate_wrap
#define MATTrackInstallWithReferenceId MATTrackInstallWithReferenceId_wrap
#define MATTrackActionForEventIdOrName MATTrackActionForEventIdOrName_wrap
#define MATTrackActionForEventIdOrNameItems MATTrackActionForEventIdOrNameItems_wrap
#define MATTrackAction MATTrackAction_wrap
#define MATSetPackageName MATSetPackageName_wrap
#define MATSetCurrencyCode MATSetCurrencyCode_wrap
#define MATSetOpenUDID MATSetOpenUDID_wrap
#define MATSetUserId MATSetUserId_wrap
#define MATSetRevenue MATSetRevenue_wrap
#define MATSetSiteId MATSetSiteId_wrap
#define MATSetTRUSTeId MATSetTRUSTeId_wrap
#define MATSetAge MATSetAge_wrap
#define MATSetGender MATSetGender_wrap
#define MATSetLocation MATSetLocation_wrap
#define MATSetDelegate MATSetDelegate_wrap
#define MATSetUseHTTPS MATSetUseHTTPS_wrap
#define MATSetJailbroken MATSetJailbroken_wrap
#define MATSetShouldAutoDetectJailbroken MATSetShouldAutoDetectJailbroken_wrap
#define MATSetShouldAutoGenerateMacAddress MATSetShouldAutoGenerateMacAddress_wrap
#define MATSetShouldAutoGenerateODIN1Key MATSetShouldAutoGenerateODIN1Key_wrap
#define MATSetShouldAutoGenerateOpenUDIDKey MATSetShouldAutoGenerateOpenUDIDKey_wrap
#define MATSetUseCookieTracking MATSetUseCookieTracking_wrap
#define MATStartAppToAppTracking MATStartAppToAppTracking_wrap
#define MATSetRedirectUrl MATSetRedirectUrl_wrap
#define MATSetAppleAdvertisingIdentifier MATSetAppleAdvertisingIdentifier_wrap
#define MATSetAppleVendorIdentifier MATSetAppleVendorIdentifier_wrap
#define MATSetShouldAutoGenerateAppleVendorIdentifier MATSetShouldAutoGenerateAppleVendorIdentifier_wrap
#define MATSetShouldAutoGenerateAppleAdvertisingIdentifier MATSetShouldAutoGenerateAppleAdvertisingIdentifier_wrap
#define MATSetDebugMode MATSetDebugMode_wrap
#define MATSetAllowDuplicates MATSetAllowDuplicates_wrap

#endif

void s3eMATSDKRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[34];
    funcPtrs[0] = (void*)MATStartMobileAppTracker;
    funcPtrs[1] = (void*)MATSDKParameters;
    funcPtrs[2] = (void*)MATTrackInstall;
    funcPtrs[3] = (void*)MATTrackUpdate;
    funcPtrs[4] = (void*)MATTrackInstallWithReferenceId;
    funcPtrs[5] = (void*)MATTrackActionForEventIdOrName;
    funcPtrs[6] = (void*)MATTrackActionForEventIdOrNameItems;
    funcPtrs[7] = (void*)MATTrackAction;
    funcPtrs[8] = (void*)MATSetPackageName;
    funcPtrs[9] = (void*)MATSetCurrencyCode;
    funcPtrs[10] = (void*)MATSetOpenUDID;
    funcPtrs[11] = (void*)MATSetUserId;
    funcPtrs[12] = (void*)MATSetRevenue;
    funcPtrs[13] = (void*)MATSetSiteId;
    funcPtrs[14] = (void*)MATSetTRUSTeId;
    funcPtrs[15] = (void*)MATSetAge;
    funcPtrs[16] = (void*)MATSetGender;
    funcPtrs[17] = (void*)MATSetLocation;
    funcPtrs[18] = (void*)MATSetDelegate;
    funcPtrs[19] = (void*)MATSetUseHTTPS;
    funcPtrs[20] = (void*)MATSetJailbroken;
    funcPtrs[21] = (void*)MATSetShouldAutoDetectJailbroken;
    funcPtrs[22] = (void*)MATSetShouldAutoGenerateMacAddress;
    funcPtrs[23] = (void*)MATSetShouldAutoGenerateODIN1Key;
    funcPtrs[24] = (void*)MATSetShouldAutoGenerateOpenUDIDKey;
    funcPtrs[25] = (void*)MATSetUseCookieTracking;
    funcPtrs[26] = (void*)MATStartAppToAppTracking;
    funcPtrs[27] = (void*)MATSetRedirectUrl;
    funcPtrs[28] = (void*)MATSetAppleAdvertisingIdentifier;
    funcPtrs[29] = (void*)MATSetAppleVendorIdentifier;
    funcPtrs[30] = (void*)MATSetShouldAutoGenerateAppleVendorIdentifier;
    funcPtrs[31] = (void*)MATSetShouldAutoGenerateAppleAdvertisingIdentifier;
    funcPtrs[32] = (void*)MATSetDebugMode;
    funcPtrs[33] = (void*)MATSetAllowDuplicates;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[34] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("s3eMATSDK", funcPtrs, sizeof(funcPtrs), flags, s3eMATSDKInit, s3eMATSDKTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int s3eMATSDKStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&s3eMATSDKRegisterExt;
    return 0;
}

int g_s3eMATSDKVal = s3eMATSDKStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    s3eMATSDKRegisterExt();
}
#endif

#endif
