/*
 * (C) 2001-2012 Marmalade. All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Marmalade.
 *
 * This file consists of source code released by Marmalade under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_MATSDK_H
#define S3E_EXT_MATSDK_H

#include <s3eTypes.h>

#define S3E_MATSDK_STRING_MAX 50

struct s3eMATTracker;

typedef struct MATSDKEventItem
{
	char		item[S3E_MATSDK_STRING_MAX];
	float 		unitPrice;
	int		quantity;
	float		revenue;
} MATSDKEventItem;

typedef struct s3eMATArray {
	void *m_items; // Items in array
	unsigned int m_count; // number of items
} s3eMATArray;
// \cond HIDDEN_DEFINES
S3E_BEGIN_C_DECL
// \endcond

/**
 * Returns S3E_TRUE if the MATSDK extension is available.
 */
s3eBool s3eMATSDKAvailable();

void s3eStartMobileAppTracker(const char* adId, const char* adKey);

void s3eSDKParameters();

void s3eTrackInstall();

void s3eTrackUpdate();

void s3eTrackInstallWithReferenceId(const char* refId);

void s3eTrackActionForEventIdOrName(const char* eventIdOrName, bool isId, const char* refId);

void s3eTrackActionForEventIdOrNameItems(const char* eventIdOrName, bool isId, const s3eMATArray* items, const char* refId, double revenueAmount, const char* currencyCode, uint8 transactionState);

void s3eTrackAction(const char* eventIdOrName, bool isId, double revenue, const char*  currency);

void s3eStartAppToAppTracking(const char* targetAppId, const char* advertiserId, const char* offerId, const char* publisherId, bool shouldRedirect);

void s3eSetPackageName(const char* packageName);

void s3eSetCurrencyCode(const char* currencyCode);

void s3eSetDeviceId(const char* deviceId);

void s3eSetOpenUDID(const char* openUDID);

void s3eSetUserId(const char* userId);

void s3eSetRevenue(double revenue);

void s3eSetSiteId(const char* siteId);

void s3eSetTRUSTeId(const char* tpid);

void s3eSetDelegate(bool enable);

void s3eSetUseHTTPS(bool enable);

void s3eSetAllowDuplicates(bool allowDuplicates);

void s3eSetShouldAutoGenerateMacAddress(bool shouldAutoGenerate);

void s3eSetShouldAutoGenerateODIN1Key(bool shouldAutoGenerate);

void s3eSetShouldAutoGenerateOpenUDIDKey(bool shouldAutoGenerate);

void s3eSetShouldAutoGenerateVendorIdentifier(bool shouldAutoGenerate);

void s3eSetShouldAutoGenerateAdvertiserIdentifier(bool shouldAutoGenerate);

void s3eSetUseCookieTracking(bool useCookieTracking);

void s3eSetRedirectUrl(const char* redirectUrl);

void s3eSetAdvertiserIdentifier(const char* advertiserId);

void s3eSetVendorIdentifier(const char* vendorId);

void s3eSetDebugResponse(bool shouldDebug);

S3E_END_C_DECL


#endif /* !S3E_EXT_MATSDK_H */
