/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EMATSDK_AUTODEFS_H
#define S3EMATSDK_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_MATSDK_NAME "s3eMATSDK"
#define S3E_EXT_MATSDK_HASH 0xbb39d6f4

#endif /* !S3EMATSDK_AUTODEFS_H */
